name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Update Python Script
        run: |
          python autoCheck/auto_check.py
      - name: Run Update README.md File
        run: |
          git add .
          git diff
          git commit -m "Auto Update README.md file"
          git push
